### PR TITLE
Updated assignment descriptions

### PR DESCRIPTION
**Pull request by tanna-1**

### CODE REVIEW

**Comment by fvogels** [comment]
Your suggestions are definitely appreciated. You would be getting cakepoints, but sadly, those glorious days are over :-(

I would simply merge your contributions directly, but I don't for a rather silly reason: we wish to be able to differentiate commits from us (lecturers) and students, and the way do that is based on the email used in commits, whether they contain 'student.ucll.be' or not.
If we were to merge your contributions directly, then (assuming you've configured git as instructed), your commits would appear in *all* student repos, and we'd get a wrong picture of commits made by the owner of the repo.

We already made this mistake once (i.e., there is a student commit in the course material repo) and had to filter out commits from that specific person in our counts, but we don't want to add more special cases to this list.

**Comment by tanna-1** [comment]
I understand, but the commits in my PRs are using the private GitHub email. I.e. the domain is "users.noreply.github.com".

**Comment by tanna-1** [comment]
Perhaps a better way to differentiate the commits between lecturers and the students would be to have a commit-msg hook on this repo that would add a suffix to the commit message? A suffix like [STUDENT]

**Comment by fvogels** [comment]
A hook would indeed do the job, at least if they do install it. Some people do seem to haphazardly skip steps :-) I should try to automate the installation, but that's a bit tricky.
But anyway, for this academic year it won't matter, we'll be happy if they manage to pull in updates. Some groups seem not to have been instructed to follow the installation guide.
There's also no guarantee that the course will be the same next year, so I'd rather focus on things that can still help this year.

**Pull request closed without merging**
